name: Extract and Print YAML

on:
  push:
    paths:
      - "batch-migration/**"  # Change this to your target subfolder
    branches:
      - main
  workflow_dispatch:

jobs:
  process_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List contents of batch-migration subfolder
        run: |
          echo "Listing contents of the batch-migration subfolder"
          ls batch-migration
          
      - name: Find new YAML file
        id: find_yaml
        run: |
          echo "Finding any YAML file in subfolder"
          FILE=$(ls batch-migration/*.yaml | head -n 1)
          echo "Found file: $FILE"
          echo "file=$FILE" >> $GITHUB_ENV

      - name: Parse YAML file
        if: env.file != ''
        uses: mikefarah/yq@v4
        with:
          args: e '.' "${{ env.file }}"

      - name: Print parsed YAML
        if: env.file != ''
        run: |
          echo "Parsing YAML file: ${{ env.file }}"
          yq e '.' "${{ env.file }}"

      - name: Convert YAML to JSON
        if: env.file != ''
        id: convert_yaml_to_json
        run: |
          echo "Converting YAML to JSON"
          cat "${{ env.file }}" | yq e -o=json > converted.json
          cat converted.json
          
      - name: Create GitHub Issue
        if: env.file != ''
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "New Issue from YAML"
          content-filepath: "${{ env.file }}"
          token: ${{ secrets.GITHUB_TOKEN }}
