name: Extract and Print YAML

on:
  push:
    paths:
      - "batch-migration/**"  # Change this to your target subfolder
    branches:
      - main
  workflow_dispatch:

jobs:
  process_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find new YAML file
        id: find_yaml
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'batch-migration/.*\.yaml' | head -n 1)
          echo "file=$FILE" >> $GITHUB_ENV

      - name: Parse and Print YAML
        if: env.file != ''
        uses: mikefarah/yq@v4
        with:
          args: e '.' "${{ env.file }}"
