name: Create Issue from YAML

on:
  push:
    paths:
      - "batch-migration/**"
    branches:
      - main

jobs:
  process_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find new YAML file
        id: find_yaml
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'subfolder/.*\.yaml' | head -n 1)
          echo "file=$FILE" >> $GITHUB_ENV

      - name: Parse YAML and Create Issue
        if: env.file != ''
        uses: mikefarah/yq@v4
        run: |
          YAML_FILE=${{ env.file }}
          BBS_SERVER_URL=$(yq e '.migration_data[0].bbs_server_url' "$YAML_FILE")
          BBS_PROJECT=$(yq e '.migration_data[0].bbs_project_name' "$YAML_FILE")
          BBS_REPO=$(yq e '.migration_data[0].bbs_repo_name' "$YAML_FILE")
          GH_TARGET_ORG=$(yq e '.migration_data[0].gh_target_org_name' "$YAML_FILE")
          PROGRAM_NAME=$(yq e '.migration_data[0].repo-props.program_name' "$YAML_FILE")
          BB_PROJECT_NAME=$(yq e '.migration_data[0].repo-props.bb_project_name' "$YAML_FILE")
          BB_REPO_NAME=$(yq e '.migration_data[0].repo-props.bb_repo_name' "$YAML_FILE")
          REPO_TYPE=$(yq e '.migration_data[0].repo-props.repo_type' "$YAML_FILE")
          PRODUCT_ID=$(yq e '.migration_data[0].repo-props.product_id' "$YAML_FILE")
          PRODUCT_UUID=$(yq e '.migration_data[0].repo-props.product_uuid' "$YAML_FILE")
          TECH_ASSET_ID=$(yq e '.migration_data[0].repo-props.tech_asset_id' "$YAML_FILE")
          TECH_ASSET_UUID=$(yq e '.migration_data[0].repo-props.tech_asset_uuid' "$YAML_FILE")
          TECH_ASSET_TAG=$(yq e '.migration_data[0].repo-props.tech_asset_tag' "$YAML_FILE")
          
          ISSUE_BODY=$(cat <<EOF

          {
            "bbs-server-url": "$BBS_SERVER_URL",
            "bbs-project": "$BBS_PROJECT",
            "bbs-repo": "$BBS_REPO",
            "gh_target_org_name": "$GH_TARGET_ORG",
            "repo-props": {
              "program_name": "$PROGRAM_NAME",
              "bb_project_name": "$BB_PROJECT_NAME",
              "bb_repo_name": "$BB_REPO_NAME",
              "repo_type": "$REPO_TYPE",
              "product_id": "$PRODUCT_ID",
              "product_uuid": "$PRODUCT_UUID",
              "tech_asset_id": "$TECH_ASSET_ID",
              "tech_asset_uuid": "$TECH_ASSET_UUID",
              "tech_asset_tag": "$TECH_ASSET_TAG"
            }
          }
          EOF
          )
          
          echo "$ISSUE_BODY" > issue.json
          
      - name: Create GitHub Issue
        if: env.file != ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "New Migration Data"
          content-filepath: ./issue.json
          labels: migration
